/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csg;

/**
 *
 * @author bingling.dong
 */
public enum SchedulePropertyType {
    SCHEDULE_PANE,
    
    CALENDAR_BOUNDARIES_LABEL,
    CALENDAR_BOUNDARIES_STARTING_LABEL,
    CALENDAR_BOUNDARIES_STARTING_DATEPICKER,
    CALENDAR_BOUNDARIES_ENDING_LABEL,
    CALENDAR_BOUNDARIES_ENDING_DATEPICKER,
    
    CALENDAR_SCHEDULE_ITEMS_REMOVE_BUTTON,
    CALENDAR_SCHEDULE_ITMES_LABEL,
    CALENDAR_SCHEDULE_ITEMS_TABLEVIEW,
    CALENDAR_SCHEUDLE_ITMES_TYPE_COLUMN,
    CALENDAR_SCHEUDLE_ITMES_DATE_COLUMN,
    CALENDAR_SCHEUDLE_ITMES_TITLE_COLUMN,
    CALENDAR_SCHEUDLE_ITMES_TOPIC_COLUMN,
    
    CALENDAR_ADD_EDIT_LABEL,
    CALENDAR_ADD_EDIT_TYPE_LABEL,
    CALENDAR_ADD_EDIT_DATE_LABEL,
    CALENDAR_ADD_EDIT_TITLE_LABEL,
    CALENDAR_ADD_EDIT_TOPIC_LABEL,
    CALENDAR_ADD_EDIT_LINK_LABEL,
    CALENDAR_ADD_EDIT_TYPE_COMBO,
    CALENDAR_ADD_EDIT_DATE_DATEPICKER,
    CALENDAR_ADD_EDIT_TITLE_TEXTFIELD,
    CALENDAR_ADD_EDIT_TOPIC_TEXTFIELD,
    CALENDAR_ADD_EDIT_LINK_TEXTFIELD,
    CALENDAR_ADD_EDIT_BUTTON,
    CALENDAR_CLEAR_BUTTON,
    
    CALENDAR_STARTDATE_FOOLPROOF_SETTING,
    CALENDAR_ENDDATE_FOOLPROOF_SETTING,
    
}
