/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csg;

/**
 *
 * @author bingling.dong
 */
public enum SitePropertyType {
    SITE_PANE,
    //BANNER
    SITE_BANNER_PANE,
    SITE_BANNER_LABEL,
    SITE_BANNER_COURSE_SUBJECT_LABEL,
    SITE_BANNER_COURSE_NUMBER_LABEL,
    SITE_BANNER_COURSE_SEMESTER_LABEL,
    SITE_BANNER_COURSE_YEAR_LABEL,
    SITE_BANNER_COURSE_TITLE_LABEL,
    SITE_BANNER_EXPORT_DIR_LABEL,

    
    SITE_BANNER_COURSE_SUBJECT_COMBO,
    SITE_BANNER_COURSE_NUMBER_COMBO,
    SITE_BANNER_COURSE_SEMESTER_COMBO,
    SITE_BANNER_COURSE_YEAR_COMBO,
    SITE_BANNER_COURSE_TITLE_TEXTFIELD,
    SITE_BANNER_EXPORT_DIR_ADDRESS,
  
    
    //PAGE
    SITE_PAGE_PANE,
    SITE_PAGE_LABEL,
    SITE_PAGE_HOME_CHECKBOX,
    SITE_PAGE_SYLLABUS_CHECKBOX,
    SITE_PAGE_SCHEDULE_CHECKBOX,
    SITE_PAGE_HWS_CHECKBOX,
    SITE_CHECKBOX_FOOLPROOF_SETTINGS,
    
    //STYLE
    SITE_STYLE_PANE,
    SITE_STYLE_LABEL,
    SITE_STYLE_FAVICON_BUTTON,
    SITE_STYLE_NAVBAR_BUTTON,
    SITE_STYLE_LEFT_FOOTER_BUTTON,
    SITE_STYLE_RIGHT_FOOTER_BUTTON,
    
    SITE_STYLE_FONT_COLORS_LABEL,
    SITE_STYLE_FONT_COLORS_COMBO,
    SITE_STYLE_FONT_NOTE_LABEL,
    SITE_STYLE_IMAGE_FAVICON_IMAGEVIEW,
    SITE_STYLE_IMAGE_NAVBAR_IMAGEVIEW,
    SITE_STYLE_IMAGE_LEFT_IMAGEVIEW,
    SITE_STYLE_IMAGE_RIGHT_IMAGEVIEW,
    
    
    
        //Invalid image
    INVALID_IMAGE_TITLE,
    IO_IMAGE_EXCEPTION_CONTENT,
    
    //INSTRUCTOR
    SITE_INSTRUCTOR_PANE,
    SITE_INSTRUCTOR_LABEL,
    SITE_INSTRUCTOR_NAME_LABEL,
    SITE_INSTRUCTOR_NAME_TEXTFIELD,
    SITE_INSTRUCTOR_ROOM_LABEL,
    SITE_INSTRUCTOR_ROOM_TEXTFIELD,
    SITE_INSTRUCTOR_EMAIL_LABEL,
    SITE_INSTRUCTOR_EMAIL_TEXTFIELD,
    SITE_INSTRUCTOR_HOMEPAGE_LABEL,
    SITE_INSTRUCTOR_HOMEPAGE_TEXTFIELD,
    SITE_INSTRUCTOR_OFFICEHOUR_TITLEDPANE,
    SITE_INSTRUCTOR_OFFICEHOUR_TEXTAREA,
    
   
    
    
    
}
