/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csg;

/**
 *
 * @author bingling.dong
 */
public enum SyllabusPropertyType {
    SYLLABUS_PANE,
    SYLLABUS_DES_TITLEDPANE,
    SYLLABUS_TOPICS_TITLEDPANE,
    SYLLABUS_PREREQ_TITLEDPANE,
    SYLLABUS_OUTCOMES_TITLEDPANE,
    SYLLABUS_TEXTBOOKS_TITLEDPANE,
    SYLLABUS_GRADEDCOM_TITLEDPANE,
    SYLLABUS_GRADING_NOTE_TITLEDPANE,
    SYLLABUS_ACADEMIC_DIS_TITLEDPANE,
    SYLLABUS_SPECIAL_ASSISTANCE_TITLEDPANE,
    
    SYLLABUS_DES_TEXTAREA,
    SYLLABUS_TOPICS_TEXTAREA,
    SYLLABUS_PREREQ_TEXTAREA,
    SYLLABUS_OUTCOMES_TEXTAREA,
    SYLLABUS_TEXTBOOKS_TEXTAREA,
    SYLLABUS_GRADEDCOM_TEXTAREA,
    SYLLABUS_GRADING_NOTE_TEXTAREA,
    SYLLABUS_ACADEMIC_DIS_TEXTAREA,
    SYLLABUS_SPECIAL_ASSISTANCE_TEXTAREA,
    
}
